import { useEffect } from 'react';
import { useLocation, useNavigate } from 'react-router-dom';
import { AlertCircle, CheckCircle2, ArrowLeft, Percent } from 'lucide-react';
import { useLang } from '../context/LangContext';
import Header from '../components/Header';

const getSimpleExplanation = (issue, lang, severity, riskLevel) => {
  const isDecay = issue.toLowerCase().includes('decay') || issue.toLowerCase().includes('carie');
  
  if (isDecay) {
    const severityText = lang === 'fr' 
      ? (severity === 'High' ? 'sévère' : severity === 'Medium' ? 'modérée' : 'légère')
      : severity.toLowerCase();
    
    return lang === 'fr' 
      ? `L'IA a détecté une carie ${severityText} avec un niveau de risque ${riskLevel.toLowerCase()}. Une consultation dentaire professionnelle est recommandée pour une évaluation complète.`
      : lang === 'ar'
      ? `اكتشف الذكاء الاصطناعي تسوساً ${severityText === 'high' ? 'شديداً' : severityText === 'medium' ? 'متوسطاً' : 'خفيفاً'}. يُنصح باستشارة طبيب أسنان لتقييم مهني.`
      : `The AI detected ${severityText} decay with ${riskLevel.toLowerCase()} risk level. Professional dental consultation is recommended for proper assessment.`;
  } 
  
  return lang === 'fr' 
    ? "L'IA a détecté une ancienne réparation dentaire. Un suivi régulier est conseillé pour maintenir la santé bucco-dentaire." 
    : "The AI detected previous dental work. Regular monitoring is advised to maintain oral health.";
};

export default function SelfieResults() {
  const location = useLocation();
  const navigate = useNavigate();
  const { lang } = useLang();

  const { result, imageUrl } = location.state || {};

  useEffect(() => {
    if (!result || !imageUrl) {
      navigate('/selfie');
    }
  }, [result, imageUrl, navigate]);

  if (!result || !imageUrl) return null;

  return (
    <div className="min-h-screen bg-[#F4F7F9] flex flex-col font-sans relative pb-20">
      <div className="absolute inset-0 z-0 pointer-events-none" style={{ backgroundImage: 'radial-gradient(#cbd5e1 1px, transparent 1px)', backgroundSize: '40px 40px', opacity: 0.3 }}></div>

      <Header />

      <main className="flex-1 max-w-5xl mx-auto w-full px-6 py-12 relative z-10">
        
        <button onClick={() => navigate('/')} className="flex items-center gap-2 text-slate-500 hover:text-slate-800 mb-8 font-medium">
          <ArrowLeft size={20} /> {lang === 'fr' ? 'Retour' : lang === 'ar' ? 'عودة' : 'Back'}
        </button>

        <div className="text-center mb-12">
          <h1 className="text-4xl md:text-5xl font-black text-slate-900 tracking-tight mb-4">
            {lang === 'fr' ? 'Analyse Dentaire' : lang === 'ar' ? 'التحليل السني' : 'Dental Analysis'}
          </h1>
          <p className="text-slate-500 text-lg">
            {lang === 'fr' ? "Résultats générés par notre modèle YOLOv8 d'intelligence artificielle." : "Results generated by our YOLOv8 AI model."}
          </p>
        </div>

        {/* OVERALL ASSESSMENT SUMMARY */}
        {result.summary && (
          <div className="mb-12">
            <div className="bg-white p-6 rounded-[2rem] shadow-lg shadow-slate-200/50 border border-slate-100">
              <div className="flex items-center justify-between mb-4">
                <h2 className="text-2xl font-bold text-slate-800">
                  {lang === 'fr' ? 'Évaluation Globale' : 'Overall Assessment'}
                </h2>
                <div className="text-lg font-semibold text-slate-600">
                  Score: {result.summary.overall_score}/5
                </div>
              </div>
              
              <div className="grid md:grid-cols-4 gap-4 mb-4">
                <div className="bg-slate-50 p-4 rounded-xl text-center">
                  <div className="text-2xl font-bold text-slate-800">{result.summary.total_detections}</div>
                  <div className="text-sm text-slate-600">
                    {lang === 'fr' ? 'Détections' : 'Detections'}
                  </div>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl text-center">
                  <div className="text-2xl font-bold text-slate-800">{result.summary.decay_count}</div>
                  <div className="text-sm text-slate-600">
                    {lang === 'fr' ? 'Caries' : 'Decay'}
                  </div>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl text-center">
                  <div className="text-2xl font-bold text-slate-800">{result.summary.affected_areas_count}</div>
                  <div className="text-sm text-slate-600">
                    {lang === 'fr' ? 'Zones affectées' : 'Affected Areas'}
                  </div>
                </div>
                <div className="bg-slate-50 p-4 rounded-xl text-center">
                  <div className="text-2xl font-bold text-slate-800">{result.summary.average_confidence}%</div>
                  <div className="text-sm text-slate-600">
                    {lang === 'fr' ? 'Confiance moyenne' : 'Avg Confidence'}
                  </div>
                </div>
              </div>
              
              <div className="bg-slate-50 p-4 rounded-xl">
                <div className="font-semibold text-slate-800 mb-1">
                  {lang === 'fr' ? 'Recommandation' : 'Recommendation'}
                </div>
                <div className="text-slate-700">
                  {result.summary.recommendation}
                </div>
              </div>
            </div>
          </div>
        )}

        <div className="grid lg:grid-cols-2 gap-12">
          
          {/* L'IMAGE AVEC LES VRAIS CADRES YOLO */}
          <div className="bg-slate-900 p-2 rounded-[2rem] shadow-2xl relative overflow-hidden h-fit border-4 border-white">
            <div className="relative w-full">
              <img src={imageUrl} alt="Patient Selfie" className="w-full h-auto rounded-[1.5rem] opacity-90" />
              
              {/* Dessin dynamique basé sur TES coordonnées */}
              {result.yolo_detections && result.yolo_detections.map((box, i) => {
                const isDecay = box.class_name.toLowerCase().includes("decay");
                const left = (box.bbox.x1 / result.image_width) * 100;
                const top = (box.bbox.y1 / result.image_height) * 100;
                const width = ((box.bbox.x2 - box.bbox.x1) / result.image_width) * 100;
                const height = ((box.bbox.y2 - box.bbox.y1) / result.image_height) * 100;

                return (
                  <div 
                    key={i}
                    className={`absolute border-2 transition-all ${isDecay ? 'border-cyan-400 bg-cyan-400/20' : 'border-emerald-400 bg-emerald-400/20'}`}
                    style={{ left: `${left}%`, top: `${top}%`, width: `${width}%`, height: `${height}%` }}
                  >
                    <span className={`absolute -top-6 left-0 text-[10px] font-bold uppercase tracking-widest text-slate-900 px-2 py-0.5 rounded shadow-lg ${isDecay ? 'bg-cyan-400' : 'bg-emerald-400'}`}>
                      {box.confidence_pct}%
                    </span>
                  </div>
                );
              })}
            </div>
          </div>

          {/* LES VRAIES EXPLICATIONS */}
          <div className="space-y-6">
            {result.findings && result.findings.length > 0 ? (
              result.findings.map((finding, i) => (
                <div key={i} className="bg-white p-6 rounded-[2rem] shadow-lg shadow-slate-200/50 border border-slate-100 relative overflow-hidden transition-all hover:-translate-y-1">
                  
                  <div className={`absolute top-0 right-0 w-24 h-24 rounded-full blur-3xl opacity-20 ${finding.is_decay ? 'bg-cyan-500' : 'bg-emerald-500'}`}></div>

                  <div className="flex gap-5 relative z-10">
                    <div className={`mt-1 flex-shrink-0 ${finding.is_decay ? 'text-cyan-500' : 'text-emerald-500'}`}>
                      {finding.is_decay ? <AlertCircle size={32} /> : <CheckCircle2 size={32} />}
                    </div>

                    <div className="w-full">
                      <div className="flex justify-between items-start mb-3">
                        <div>
                          <p className="text-sm font-bold text-slate-400 uppercase tracking-widest mb-1">
                            {lang === 'fr' ? 'Zone détectée' : 'Location'}
                          </p>
                          <h3 className="text-xl font-black text-slate-800">
                            {finding.tooth}
                          </h3>
                        </div>
                        
                        <div className="flex flex-col items-end gap-2">
                          <div className={`flex items-center gap-1 font-black text-lg ${finding.is_decay ? 'text-cyan-500' : 'text-emerald-500'}`}>
                            {finding.probability} <Percent size={16} strokeWidth={3} />
                          </div>
                          
                          {finding.severity && (
                            <div className={`px-3 py-1 rounded-full text-xs font-bold border ${
                              finding.severity === 'High' ? 'text-red-600 bg-red-50 border-red-200' :
                              finding.severity === 'Medium' ? 'text-orange-600 bg-orange-50 border-orange-200' :
                              'text-yellow-600 bg-yellow-50 border-yellow-200'
                            }`}>
                              {finding.severity}
                            </div>
                          )}
                        </div>
                      </div>

                      {finding.risk_level && (
                        <div className="flex items-center gap-2 mb-3">
                          <div className={`flex items-center gap-1 text-sm font-medium ${
                            finding.risk_level === 'Urgent' ? 'text-red-600' :
                            finding.risk_level === 'Monitor' ? 'text-orange-600' :
                            'text-green-600'
                          }`}>
                            {finding.risk_level === 'Urgent' ? '⚠️' :
                             finding.risk_level === 'Monitor' ? '👁️' : '✅'}
                            {lang === 'fr' ? 'Niveau de risque:' : 'Risk Level:'} {finding.risk_level}
                          </div>
                        </div>
                      )}

                      <div className="bg-slate-50 p-4 rounded-2xl border border-slate-100">
                        <p className="text-slate-700 font-medium leading-relaxed">
                          {getSimpleExplanation(finding.issue, lang, finding.severity, finding.risk_level)}
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              ))
            ) : (
              <div className="bg-white p-10 rounded-[2rem] text-center border border-slate-100 shadow-sm">
                <CheckCircle2 size={64} className="mx-auto text-teal-400 mb-4" />
                <h3 className="text-2xl font-bold text-slate-800 mb-2">
                  {lang === 'fr' ? 'Excellente Santé Buccale' : 'Excellent Oral Health'}
                </h3>
                <p className="text-slate-500">
                  {lang === 'fr' 
                    ? "Notre IA n'a détecté aucune anomalie visible sur cette photo. Continuez vos bonnes habitudes d'hygiène bucco-dentaire avec des contrôles réguliers." 
                    : "Our AI didn't detect any visible anomalies in this photo. Continue your good oral hygiene habits with regular check-ups."}
                </p>
              </div>
            )}
          </div>

        </div>
      </main>
    </div>
  );
}
